---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sonarr
    template:
      data:
        SONARR__AUTH__APIKEY: "{{ .sonarr_api_key }}"
  dataFrom:
    - extract:
        key: sonarr
