apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app valkey
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      main:
        containers:
          valkey:
            image:
              repository: valkey/valkey
              pullPolicy: IfNotPresent
              tag: 8.1.3-alpine
            resources:
              requests:
                cpu: 30m
                memory: 128Mi
            probes:
              liveness: &server_probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 6379
                  periodSeconds: 30
                  timeoutSeconds: 1
                  failureThreshold: 5
              readiness: *server_probes
              startup:
                enabled: false
    service:
      valkey:
        controller: main
        ports:
          valkey:
            port: 6379
