apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app satisfactory
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
    controllers:
      satisfactory:
        containers:
          app:
            image:
              repository: janpuc/satisfactory-arm64
              tag: 0.0.1
            env:
              ALWAYS_UPDATE_ON_START: true
              EXTRA_PARAMS: -log -unattended -ini:Engine:[HTTPServer.Listeners]:DefaultBindAddress=any
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      app:
        annotations:
          oci.oraclecloud.com/load-balancer-type: "nlb"
          oci-network-load-balancer.oraclecloud.com/oci-network-security-groups: "${lb_nsg_id}"
          oci-network-load-balancer.oraclecloud.com/security-list-management-mode: all
          service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
          service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
          service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
        controller: satisfactory
        type: LoadBalancer
        ports:
          api:
            port: &api 7777
            targetPort: *api
            protocol: TCP
          game:
            port: &game 7777
            targetPort: *game
            protocol: UDP
          messaging:
            port: &messaging 8888
            targetPort: *messaging
            protocol: TCP
    persistence:
      satisfactory:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: local-hostpath
        size: 20Gi
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: local-hostpath
        size: 1Gi
        globalMounts:
          - path: /config:/home/steam/.config/Epic
