apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: lldap-db
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .db_user }}"
        password: "{{ .db_pass }}"
  dataFrom:
    - extract:
        key: lldap
