---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app factorio
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      autobrr:
        containers:
          app:
            image:
              repository: factoriotools/factorio
              tag: 2.0.69
            env:
              PORT: &port 34197
              BIND: 0.0.0.0
              GENERATE_NEW_SAVE: true
              SAVE_NAME: "BiangBiangWorld2"
              PRESET: rail-world
              DLC_SPACE_AGE: false
            probes:
              liveness: &probes
                enabled: false
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - "ALL"
            resources:
              requests:
                cpu: 1
              limits:
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 845
        runAsGroup: 845
        fsGroup: 845
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        annotations:
          lbipam.cilium.io/ips: 10.69.21.128
          lbipam.cilium.io/sharing-key: main
          lbipam.cilium.io/sharing-cross-namespace: "*"
        type: LoadBalancer
        ports:
          factorio:
            port: *port
            protocol: UDP
    persistence:
      factorio:
        existingClaim: factorio
