---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authelia-db
    template:
      data:
        db_name: "{{ .db_name }}"
        db_user: "{{ .db_user }}"
        db_pass: "{{ .db_pass }}"
  dataFrom:
    - extract:
        key: authelia
