apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authelia-oidc
    template:
      engineVersion: v2
      data:
        oidc_jwk_key: "{{ .oidc_jwk_key | b64dec }}"
        grafana_oidc_client_secret_digest: "{{ .grafana_oidc_client_secret_digest }}"
        autobrr_oidc_client_secret_digest: "{{ .autobrr_oidc_client_secret_digest }}"
  dataFrom:
    - extract:
        key: authelia
    - extract:
        key: autobrr
    - extract:
        key: grafana
