apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authelia-oidc
    template:
      data:
        grafana_oidc_client_secret: "{{ .grafana_oidc_client_secret }}"
  dataFrom:
    - extract:
        key: grafana
