---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: medibrowserr
spec:
  components:
    - ../../../../components/zeroscaler
    - ../../../../components/kopiur/backup
  dependsOn:
    - name: miroir-config
      namespace: miroir-system
  interval: 1h
  path: ./kubernetes/apps/selfhosted/medibrowserr/app
  postBuild:
    substitute:
      APP: medibrowserr
      KOPIUR_COPYMETHOD: Direct
      KOPIUR_STORAGECLASS: miroir-fast-local
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  wait: false
