---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: open-webui-secret
    template:
      data:
        HF_TOKEN: "{{ .LLAMA_CPP_HF_TOKEN }}"
        LLAMA_API_KEY: "{{ .LLAMA_CPP_API_KEY }}"
  dataFrom:
    - extract:
        key: llama-cpp
