---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minimax-shim
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: minimax-shim-secret
    template:
      data:
        MINIMAX_API_KEY: "{{ .MINIMAX_API_KEY }}"
        SHIM_API_KEY: "{{ .SHIM_API_KEY }}"
  dataFrom:
    - extract:
        key: minimax-shim
