---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: jellyfin
    template:
      data:
        jellyfin_ip: "{{ .ip }}"
  dataFrom:
    - extract:
        key: jellyfin
