---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: unifi
    template:
      data:
        host: "{{ .host }}"
        api_key: "{{ .api_key }}"
  dataFrom:
    - extract:
        key: unifi
