---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/kubernetes-sigs/agent-sandbox/v0.5.6/helm/crds/agents.x-k8s.io_sandboxes.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/agent-sandbox/v0.5.6/helm/crds/extensions.agents.x-k8s.io_sandboxclaims.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/agent-sandbox/v0.5.6/helm/crds/extensions.agents.x-k8s.io_sandboxtemplates.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/agent-sandbox/v0.5.6/helm/crds/extensions.agents.x-k8s.io_sandboxwarmpools.yaml
patches:
  - target:
      kind: CustomResourceDefinition
    patch: |-
      - op: replace
        path: /spec/conversion/webhook/clientConfig/service/namespace
        value: ai
