---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./agents.x-k8s.io_sandboxes.yaml
  - ./extensions.agents.x-k8s.io_sandboxclaims.yaml
  - ./extensions.agents.x-k8s.io_sandboxtemplates.yaml
  - ./extensions.agents.x-k8s.io_sandboxwarmpools.yaml
patches:
  - target:
      kind: CustomResourceDefinition
    patch: |-
      - op: replace
        path: /spec/conversion/webhook/clientConfig/service/namespace
        value: ai
