---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tuiter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tuiter-secret
    template:
      data:
        TUITER_LITELLM_API_KEY: "{{ .LITELLM_MASTER_KEY }}"
        TUITER_POSTER_HANDLE: "{{ .POSTER_HANDLE }}"
        TUITER_READER_HANDLE: "{{ .READER_HANDLE }}"
  dataFrom:
    - extract:
        key: tuiter
    - extract:
        key: litellm
