---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tuiter-reader-profile
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    apiGroup: kopiur.home-operations.com
    kind: Restore
    name: tuiter-reader-profile
  resources:
    requests:
      storage: 5Gi
  storageClassName: miroir-fast-local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tuiter-poster-profile
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    apiGroup: kopiur.home-operations.com
    kind: Restore
    name: tuiter-poster-profile
  resources:
    requests:
      storage: 5Gi
  storageClassName: miroir-fast-local
