---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tuiter-reader-profile
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: miroir-fast
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tuiter-poster-profile
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: miroir-fast
