---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renplay
spec:
  chartRef:
    kind: OCIRepository
    name: renplay
  interval: 1h
  values:
    controllers:
      komf:
        containers:
          app:
            image:
              repository: ghcr.io/janpuc/renplay
              tag: edge@sha256:31138c2c59bb686ba351c99bec1559ef23a2560963ba8d4ab85f5f7247f86ceb
            env:
              TZ: Europe/Warsaw
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: &port 8080
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.janpuc.com"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: bigmouth.internal
        path: /mnt/Vault/Media/Games
        globalMounts:
          - path: /games
      tmp:
        type: emptyDir
