---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: autobrr
spec:
  name: Autobrr
  callbackUrls:
    - "https://autobrr.janpuc.com/api/auth/oidc/callback"
  allowedUserGroups:
    - name: id-admin
      namespace: security
  secret:
    keys:
      clientID: AUTOBRR__OIDC_CLIENT_ID
      clientSecret: AUTOBRR__OIDC_CLIENT_SECRET
