apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authelia
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    pod:
      kind: Deployment
      replicas: 1 # TODO: Bump up after debugging
    configMap:
      theme: auto
      default_2fa_method: totp
      authentication_backend:
        password_reset:
          disable: true
        password_change:
          disable: true
        ldap:
          enabled: true
          address: ldap://lldap.security.svc.cluster.local:8389
          implementation: custom
          base_dn: ${lldap_base_dn}
          additional_users_dn: ou=people
          users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
          additional_groups_dn: ou=groups
          groups_filter: (member={dn})
          user: uid=${lldap_user_dn},ou=people,${lldap_base_dn}
          password:
            disabled: false
            secret_name: authelia-lldap
            path: password
          attributes:
            username: uid
            display_name: displayName
            mail: mail
            member_of: memberOf
            group_name: cn
      access_control:
        default_policy: bypass
        rules: []
      session:
        cookies:
          - domain: ${domain}
            authelia_url: https://auth.${domain}
            default_redirection_url: https://home.${domain} # INFO: Homepage
        redis:
          enabled: true
          host: valkey.storage.svc.cluster.local
          port: 6379
          database_index: 10
          password:
            disabled: true
      storage:
        postgres:
          enabled: true
          address: tcp://aetherdb-rw.storage.svc.cluster.local:5432
          database: ${db_name}
          username: ${db_user}
          password:
            disabled: false
            secret_name: authelia-db
            path: password
      notifier:
        disable_startup_check: true
        filesystem:
          enabled: true
          filename: '/config/notification.txt'
      identity_providers:
        oidc:
          enabled: true
          jwks:
            - key:
                path: '/secrets/authelia-oidc/jwk.RS256.pem'
          claims_policies:
            grafana:
              id_token: ['email', 'name', 'groups', 'preferred_username']
          clients:
          - client_id: autobrr
            client_name: Autobrr
            client_secret:
              path: '/secrets/authelia-oidc/autobrr'
            public: false
            authorization_policy: one_factor # TODO: Change after correct 2nd factor setup done
            redirect_uris:
              - https://autobrr.${domain}/api/auth/oidc/callback
            scopes:
              - openid
              - profile
              - groups
              - email
            token_endpoint_auth_method: client_secret_post
          - client_id: grafana
            client_name: Grafana
            client_secret:
              path: '/secrets/authelia-oidc/grafana'
            public: false
            authorization_policy: one_factor # TODO: Change after correct 2nd factor setup done
            require_pkce: true
            pkce_challenge_method: S256
            redirect_uris:
              - https://grafana.${domain}/login/generic_oauth
            scopes:
              - openid
              - profile
              - groups
              - email
            response_types:
              - code
            grant_types:
              - authorization_code
            access_token_signed_response_alg: none
            userinfo_signed_response_alg: none
            token_endpoint_auth_method: client_secret_basic
          - client_id: jellyfin
            client_name: Jellyfin
            client_secret:
              path: '/secrets/authelia-oidc/jellyfin'
            public: false
            authorization_policy: one_factor # TODO: Change after correct 2nd factor setup done
            require_pkce: true
            pkce_challenge_method: S256
            redirect_uris:
              - https://jellyfin.${domain}/sso/OID/redirect/authelia
            scopes:
              - openid
              - profile
              - groups
            access_token_signed_response_alg: none
            userinfo_signed_response_alg: none
            token_endpoint_auth_method: client_secret_post
    secret:
      additionalSecrets:
        authelia-lldap:
          items:
            - key: lldap_user_pass
              path: password
        authelia-db:
          items:
            - key: db_pass
              path: password
        authelia-oidc:
          items:
            - key: oidc_jwk_key
              path: jwk.RS256.pem
            - key: autobrr_oidc_client_secret_digest
              path: autobrr
            - key: grafana_oidc_client_secret_digest
              path: grafana
            - key: jellyfin_oidc_client_secret_digest
              path: jellyfin
