apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authelia
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    configMap:
      theme: auto
      default_2fa_method: totp
      user_attributes: {}
      authentication_backend:
        password_reset:
          disable: true
        password_change:
          disable: true
        ldap:
          enabled: true
          address: ldap://lldap.security.svc.cluster.local:8389
          implementation: custom
          base_dn: ${lldap_base_dn}
          additional_users_dn: ou=people
          users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
          additional_groups_dn: ou=groups
          groups_filter: (member={dn})
          group_search_mode: filter
          user: uid=${lldap_user_dn},ou=people,${lldap_base_dn}
          password:
            disabled: false
            secret_name: authelia-lldap
            path: password
          attributes:
            username: uid
            display_name: displayName
            mail: mail
            member_of: memberOf
            group_name: cn
      access_control:
        default_policy: bypass
        rules: []
      session:
        cookies:
          - domain: ${domain}
            authelia_url: https://auth.${domain}
            default_redirection_url: https://home.${domain} # INFO: Homepage
        redis:
          enabled: true
          enabledSecret: false
          host: valkey.storage.svc.cluster.local
          port: 6379
          database_index: 10
          password:
            disabled: true
      storage:
        postgres:
          enabled: true
          address: tcp://aetherdb-rw.storage.svc.cluster.local:5432
          database: ${db_name}
          username: ${db_user}
          password:
            disabled: false
            secret_name: authelia-db
            path: password
      notifier:
        disable_startup_check: true
        filesystem:
          enabled: true
          filename: '/config/notification.txt'
    secret:
      additionalSecrets:
        authelia-lldap:
          items:
            - key: lldap_user_pass
              path: password
        authelia-redis:
          items:
            - key: redis_pass
              path: password
        authelia-db:
          items:
            - key: db_pass
              path: password
