apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-ccm
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: proxmox-ccm
    template:
      data:
        config.yaml: |-
          clusters:
            - url: "{{ .endpoint }}/api2/json"
              insecure: true
              token_id: "{{ .token_id }}"
              token_secret: "{{ .token_secret }}"
              region: aether
  dataFrom:
    - extract:
        key: proxmox-ccm-aether
