apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app istiod
  namespace: &namespace istio-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  path: ./kubernetes/apps/_base/istio-system/istiod/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
  values:
    global:
      ambient: true
      logging:
        level: "default:info"
      proxy:
        autoInject: disabled
    pilot:
      appNamespaces: ["*"] 
      env:
        PILOT_ENABLE_AMBIENT: "true"
        PILOT_ENABLE_WAYPOINT: "false"
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
    ztunnel:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - operator: Exists
    cni:
      enabled: false
    meshConfig:
      enableAutoMtls: true
      protocolDetectionTimeout: 100ms
