---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authelia
  namespace: &namespace security
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: authelia-db
      namespace: security # TODO: No clue why it's different than the one below
    - name: authelia-secrets
      namespace: security
    - name: common-secrets
      namespace: external-secrets
  interval: 30m
  path: ./kubernetes/apps/_base/security/authelia/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: common-data
      - kind: Secret
        name: authelia-db
      - kind: Secret
        name: authelia-lldap
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authelia-db
  namespace: &namespace storage # TODO: Replace after this is merged https://github.com/cloudnative-pg/cloudnative-pg/issues/6043
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cnpg-cluster
      namespace: storage
  interval: 30m
  path: ./kubernetes/apps/_base/security/authelia/db
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authelia-secrets
  namespace: &namespace security
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
  interval: 30m
  path: ./kubernetes/apps/_base/security/authelia/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
