apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onepassword-connect
  namespace: flux-system
spec:
  interval: 12h
  url: https://1password.github.io/connect-helm-charts/
