apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app istio-ingressgateway
  namespace: &namespace istio-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: istio-ingressgateway-secrets
      namespace: istio-system
  interval: 30m
  path: ./kubernetes/apps/_base/istio-system/istio-ingressgateway/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: istio-ingressgateway-data
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app istio-ingressgateway-secrets
  namespace: &namespace istio-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
  interval: 30m
  path: ./kubernetes/apps/_base/istio-system/istio-ingressgateway/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true