apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: podinfo-gateway
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      oci.oraclecloud.com/load-balancer-type: "nlb"
      oci-network-load-balancer.oraclecloud.com/is-preserve-source: false
  listeners:
    - protocol: HTTP
      port: 80
      name: podinfo-route
      allowedRoutes:
        namespaces:
          from: Same
