apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyseerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: jellyseerr
    template:
      data:
        API_KEY: "{{ .jellyseerr_api_key }}"
  dataFrom:
    - extract:
        key: jellyseerr
