---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hetzner-smb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hetzner-smb
    template:
      data:
        source: "{{ .source }}"
        media_vault: "{{ .media_vault }}"
        username: "{{ .share_username }}"
        password: "{{ .share_password }}"
  dataFrom:
    - extract:
        key: hetzner
