apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-creds
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: s3-creds
    template:
      data:
        access_key: "{{ .s3_access_key }}"
        secret_key: "{{ .s3_secret_key }}"
        region: "{{ .s3_region }}"
  dataFrom:
    - extract:
        key: cnpg
