---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-mcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-mcp-secret
    template:
      data:
        GITHUB_PERSONAL_ACCESS_TOKEN: "{{ .GITHUB_PAT }}"
  dataFrom:
    - extract:
        key: github-mcp
