---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: github-mcp
spec:
  image: ghcr.io/github/github-mcp-server:v1.3.0
  transport: stdio
  groupRef:
    name: mcp-tools
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          resources:
            limits:
              memory: 48Mi
            requests:
              cpu: 10m
              memory: 32Mi
  resources:
    limits:
      memory: 96Mi
    requests:
      cpu: 10m
      memory: 48Mi
  secrets:
    - name: github-mcp-secret
      key: GITHUB_PERSONAL_ACCESS_TOKEN
