---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: context7-mcp
spec:
  groupRef:
    name: mcp-tools
  image: ghcr.io/stacklok/dockyard/npx/context7:3.2.4
  proxyPort: 8080
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          resources:
            limits:
              memory: 224Mi
            requests:
              cpu: 10m
              memory: 160Mi
  resources:
    limits:
      memory: 48Mi
    requests:
      cpu: 10m
      memory: 32Mi
  secrets:
    - name: context7-mcp-secret
      key: CONTEXT7_API_KEY
      targetEnvName: CONTEXT7_API_KEY
  transport: stdio
