apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app qbittools
spec:
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
        - name: *app
          image: janpuc/qbittools:0.0.3
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vault
      volumes:
        - name: vault
          persistentVolumeClaim:
            claimName: vault
