---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app autobrr
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: vault
      namespace: media
    - name: onepassword-store
      namespace: external-secrets
    - name: common-secrets
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/aether/media/autobrr/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
  postBuild:
    substituteFrom:
      - kind: Secret
        name: common-data
