---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: t3-code-operator
spec:
  chartRef:
    kind: OCIRepository
    name: t3-code-operator
  interval: 15m
  install:
    crds: CreateReplace
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    disableWait: true
    remediation:
      retries: 3
  values:
    operator:
      image:
        repository: ghcr.io/janpuc/t3-code-operator
        tag: ""
        digest: sha256:b8a20942b44de0d549cbacfd15d64e8ad11aa55b723919835622a5baa8004bb0
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          memory: 512Mi
    smb:
      image:
        repository: ghcr.io/janpuc/t3-code-smbd
        tag: ""
        digest: sha256:3efca7ed04e067221459a18a03a5f6581ba5fbcecd8728f60e532bdf957af209
    rbac:
      secretResourceNames:
        - t3-code-config
        - t3-code-git-signing
