---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: litellm-secret
    template:
      data:
        # App
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        # API
        OPENCODE_GO_API_KEY: "{{ .LITELLM_OPENCODE_API_KEY }}"
        LLAMA_API_KEY: "{{ .LLAMA_CPP_API_KEY }}"
  dataFrom:
    - extract:
        key: llama-cpp
    - extract:
        key: litellm
