---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: octoeverywhere
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: octoeverywhere-secret
    template:
      data:
        ACCESS_CODE: "{{ .ACCESS_CODE }}"
        SERIAL_NUMBER: "{{ .SERIAL_NUMBER }}"
        PRINTER_IP: "{{ .PRINTER_IP }}"
  dataFrom:
    - extract:
        key: bambu-a1
