---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: octoeverywhere
spec:
  chartRef:
    kind: OCIRepository
    name: octoeverywhere
  interval: 1h
  values:
    controllers:
      octoeverywhere:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/octoeverywhere/octoeverywhere
              tag: 4.6.8@sha256:3b3480d9f3520cde8ddaa0b7addb9714c44e6e82f0ec26fc467d9a4e4df9f379
            env:
              COMPANION_MODE: bambu
              CONNECTION_MODE: local
              LAN_ONLY_MODE: "true"
              TZ: Europe/Warsaw
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
