apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencryt
spec:
  acme:
    email: ${email}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencryt-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare
            key: api_token
      selector:
        dnsZones:
        - ${domain}
