---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: qui
spec:
  name: Qui
  callbackUrls:
    - "https://qui.janpuc.com/api/auth/oidc/callback"
  allowedUserGroups:
    - name: id-admin
      namespace: security
  secret:
    keys:
      clientID: QUI__OIDC_CLIENT_ID
      clientSecret: QUI__OIDC_CLIENT_SECRET
