apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-ccm
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: proxmox-ccm
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    existingConfigSecret: proxmox-ccm
    enabledControllers:
      - cloud-node
      - cloud-node-lifecycle
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
