---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
components:
  - ../../../components/common
resources:
  - ./cert-manager/ks.yaml
  - ./cloudflare-secrets/ks.yaml
  - ./external-dns/ks.yaml
  - ./gateway/ks.yaml
  - ./nginx/ks.yaml
