apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - ./namespace.yaml
  - ./external-dns/install.yaml
  - ./gateway/install.yaml
  # - ./tailscale/install.yaml
