---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./dashboards/aether-fleet/
  - ./externalsecret.yaml
  - ./grafanadashboard-aether-a2a-activity.yaml
  - ./grafanadashboard-aether-fleet-health.yaml
  - ./grafanadashboard-aether-harness-quota.yaml
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
