apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hetzner-smb
provisioner: smb.csi.k8s.io
parameters:
  source: //${source}
  csi.storage.k8s.io/provisioner-secret-name: hetzner-smb
  csi.storage.k8s.io/provisioner-secret-namespace: storage
  csi.storage.k8s.io/node-stage-secret-name: hetzner-smb
  csi.storage.k8s.io/node-stage-secret-namespace: storage
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino
