---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hermes-k8s
spec:
  components:
    - ../../../../components/kopiur/backup
    - ../../../../components/hermes-agent
  dependsOn:
    - name: litellm
      namespace: ai
    - name: memini
      namespace: ai
  interval: 1h
  path: ./kubernetes/apps/ai/hermes-k8s/app
  postBuild:
    substitute:
      APP: hermes-k8s
      HERMES_AGENT_ID: K8S
      HERMES_MEMINI_NAMESPACE: homelab/home-ops
      KOPIUR_COPYMETHOD: Direct
      KOPIUR_STORAGECLASS: miroir-fast-local
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  wait: false
