---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
spec:
  chartRef:
    kind: OCIRepository
    name: minecraft
  interval: 1h
  values:
    deploymentAnnotations:
      secret.reloader.stakater.com/reload: &secret minecraft
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: 2026.2.0-java21
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 4Gi
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    livenessProbe:
      initialDelaySeconds: 0
    readinessProbe:
      initialDelaySeconds: 0
    startupProbe:
      enabled: true
    extraEnv:
      TZ: "Europe/Warsaw"
      UID: 1000
      GID: 1000
      MEMORY: ""
    persistence:
      dataDir:
        enabled: true
        existingClaim: "${APP}"
    serviceAnnotations:
      lbipam.cilium.io/ips: "192.168.69.61"
    minecraftServer:
      eula: true
      version: 1.21.1
      type: FABRIC
      difficulty: normal
      pvp: false
      motd: "Socialist Utopia"
      worldSaveName: "Socialist Utopia"
      viewDistance: 12
      forceReDownload: true
      memory: ""
      jvmXXOpts: "-XX:MaxRAMPercentage=70"
      rcon:
        enabled: true
        serviceType: ClusterIP
      serviceType: LoadBalancer
      extraPorts:
        - name: map
          containerPort: 8100
          protocol: TCP
          service:
            enabled: true
            embedded: false
            type: ClusterIP
            port: 8100
        - name: metrics
          containerPort: 25585
          protocol: TCP
          service:
            enabled: true
            embedded: false
            type: ClusterIP
            port: 25585
      modrinth:
        projects:
          - appleskin:3.0.6+mc1.21
          - architectury-api:13.0.8+fabric
          - athena-ctm:4.0.2
          - chunk-loaders:1.2.9-fabric-mc1.21.1
          - distanthorizons:2.4.5-b-1.21.1
          - essential-commands:0.35.2-mc1.21
          - fabricexporter:1.0.11
          - ferrite-core:7.0.3-fabric
          - geckolib:4.8.3
          - jade:15.10.5+fabric
          - journeymap:1.21.1-6.0.0-beta.54+fabric
          - lithium:mc1.21.1-0.15.2-fabric
          - modernfix:5.25.1+mc1.21.1
          - oritech:1.0.1
          - owo-lib:0.12.15.4+1.21
          - spark:1.10.109-fabric
        downloadDependencies: required
  valuesFrom:
    - kind: Secret
      name: *secret
      valuesKey: RCON_PASSWORD
      targetPath: minecraftServer.rcon.password
