apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hetzner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hetzner
    template:
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        share: "{{ .share }}"
  dataFrom:
    - extract:
        key: hetzner
