apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hetzner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hetzner
    template:
      data:
        source: "{{ .source }}"
        username: "{{ .share_username }}"
        password: "{{ .share_password }}"
  dataFrom:
    - extract:
        key: hetzner
