apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: common-data
spec:
  externalSecretName: common-data
  namespaceSelectors:
  - matchLabels:
      common-data: "true"
  refreshTime: "1h"
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword
    refreshInterval: "1h"
    target:
      name: common-data
      template:
        data:
          domain: "{{ .domain }}"
    dataFrom:
      - extract:
          key: common-k8s
