---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/toolhive.stacklok.dev/mcpoidcconfig_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPOIDCConfig
metadata:
  name: mcp-gateway-oidc
spec:
  type: inline
  inline:
    issuer: https://mcp.janpuc.com
    jwksAllowPrivateIP: true
