---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/virtualmcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: VirtualMCPServer
metadata:
  name: mcp-gateway
spec:
  authServerConfig:
    issuer: https://mcp.janpuc.com
    signingKeySecretRefs:
      - name: toolhive-secret
        key: signing_key
    hmacSecretRefs:
      - name: toolhive-secret
        key: hmac_key
    tokenLifespans:
      accessTokenLifespan: 1h
      refreshTokenLifespan: 168h
      authCodeLifespan: 10m
    upstreamProviders:
      - name: pocket-id
        type: oidc
        oidcConfig:
          issuerUrl: https://id.janpuc.com
          clientId: 49821516-f734-4dc4-85d8-386fa7ff635b
          clientSecretRef:
            name: toolhive-oidc-credentials
            key: client_secret
          redirectUri: https://mcp.janpuc.com/oauth/callback
          scopes:
            - openid
            - profile
            - email
  groupRef:
    name: mcp-tools
  config:
    aggregation:
      conflictResolution: prefix
      conflictResolutionConfig:
        prefixFormat: "{workload}_"
  incomingAuth:
    type: oidc
    oidcConfigRef:
      name: mcp-gateway-oidc
      audience: https://mcp.janpuc.com/mcp
      resourceUrl: https://mcp.janpuc.com/mcp
  outgoingAuth:
    source: discovered
  podTemplateSpec:
    spec:
      containers:
        - name: vmcp
          env:
            - name: INSECURE_DISABLE_URL_VALIDATION
              value: "true"
          requests:
            cpu: 10m
            memory: 224Mi
          limits:
            memory: 320Mi
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/virtualmcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: VirtualMCPServer
metadata:
  name: mcp-gateway-internal
spec:
  groupRef:
    name: mcp-tools
  config:
    groupRef: mcp-tools
    aggregation:
      conflictResolution: prefix
      conflictResolutionConfig:
        prefixFormat: "{workload}_"
  incomingAuth:
    type: anonymous
  outgoingAuth:
    source: discovered
  podTemplateSpec:
    spec:
      containers:
        - name: vmcp
          requests:
            cpu: 10m
            memory: 224Mi
          limits:
            memory: 320Mi
