---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: medibrowserr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: medibrowserr-secret
    template:
      data:
        MEDICOVER_USER: "{{ .MEDICOVER_USER }}"
        MEDICOVER_PASS: "{{ .MEDICOVER_PASS }}"
        PUSHOVER_TOKEN: "{{ .PUSHOVER_TOKEN }}"
  dataFrom:
    - extract:
        key: medibrowserr
