---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app metrics-server
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    args:
      - --kubelet-insecure-tls
      - --metric-resolution=30s
      - --kubelet-request-timeout=10s
    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
