apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app grafana
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    grafana.ini:
      analytics:
        check_for_updates: false
        check_for_plugin_updates: false
        reporting_enabled: false
      server:
        root_url: https://grafana.${domain}
      auth:
        disable_login_form: true
      auth.generic_oauth:
        enabled: true
        name: Authelia
        icon: signin
        client_id: grafana
        scopes:
          - openid
          - profile
          - groups
          - email
        empty_scopes: false
        auth_url: https://auth.${domain}/api/oidc/authorization
        token_url: http://authelia.security.svc.cluster.local/api/oidc/token
        api_url: http://authelia.security.svc.cluster.local/api/oidc/userinfo
        login_attribute_path: preferred_username
        groups_attribute_pat: groups
        name_attribute_path: name
        use_pkce: true
        # role_attribute_path:
      # auth.anonymous:
      #   enabled: true
      #   org_id: 1
      #   org_name: Main Org.
      #   org_role: Admin # Enable default admin access until it will be exposed
      news:
        news_feed_enabled: false
    envValueFrom:
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
        secretKeyRef:
          name: grafana-secrets
          key: grafana_oidc_client_secret
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            uid: prometheus
            access: proxy
            url: http://thanos-query.observability.svc.cluster.local:9090
            isDefault: true
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: default
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        k8s-views-global:
          gnetId: 15757
          revision: 43
          datasource: Prometheus
        k8s-views-namespaces:
          gnetId: 15758
          revision: 42
          datasource: Prometheus
        k8s-views-nodes:
          gnetId: 15759
          revision: 37
          datasource: Prometheus
        k8s-views-pods:
          gnetId: 15760
          revision: 36
          datasource: Prometheus
        k8s-system-api-server:
          gnetId: 15761
          revision: 19
          datasource: Prometheus
        k8s-system-coredns:
          gnetId: 15762
          revision: 21
          datasource: Prometheus
        k8s-addons-prometheus:
          gnetId: 19105
          revision: 7
          datasource: Prometheus
    sidecar:
      image:
        registry: ghcr.io
        repository: home-operations/k8s-sidecar
        tag: 1.30.10
      dashboards:
        enabled: true
        searchNamespace: ALL
        label: grafana_dashboard
        folderAnnotation: grafana_folder
        provider:
          disableDelete: true
          foldersFromFilesStructure: true
      datasources:
        enabled: true
        searchNamespace: ALL
        labelValue: ""
    route:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns-managed: "true"
        hostnames:
          - grafana.${domain}
        parentRefs:
          - name: main-gateway
            namespace: network
            sectionName: wildcard-domain-https
