---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    common-data: "true"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
