---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      qbittorrent:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.2
            env:
              TZ: Europe/Warsaw
              QBT_WEBUI_PORT: &port 8080
              QBT_TORRENTING_PORT: 50469
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - "ALL"
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 18Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    configMaps:
      config:
        data:
          .qbt.toml: |-
            [qbittorrent]
            addr = "http://localhost:8800"
    persistence:
      config:
        existingClaim: *app
      config-file:
        type: configMap
        name: *app
        globalMounts:
          - path: /config/.qbt.toml
            subPath: .qbt.toml
            readOnly: true
      vault:
        existingClaim: vault
      qbrr:
        type: image
        image: ghcr.io/buroa/qbrr:0.1.1
        globalMounts:
          - readOnly: true
      tmp:
        type: persistentVolumeClaim
        suffix: tmp
        accessMode: ReadWriteOnce
        size: 100Gi
