---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

components:
  - ../../components/alerts
  - ../../components/kopiur/secret

resources:
  - ./namespace.yaml
  - ./context7-mcp/ks.yaml
  - ./github-mcp/ks.yaml
  - ./ha-mcp/ks.yaml
  - ./kubectl-mcp/ks.yaml
  # - ./memory-mcp/ks.yaml
  - ./litellm/ks.yaml
  - ./litellm-operator/ks.yaml
  - ./llmkube/ks.yaml
  - ./open-webui/ks.yaml
  # - ./prometheus-mcp/ks.yaml
  - ./sidero-mcp/ks.yaml
  - ./toolhive/ks.yaml
  # - ./victoria-logs-mcp/ks.yaml
