apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 0.23.0
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    # TODO: Replace after configuring DB and Redis
    authentik:
      secret_key: "PleaseGenerateA50CharKey"
      postgresql:
        password: "ThisIsNotASecurePassword"
    postgresql:
      enabled: true
      auth:
        password: "ThisIsNotASecurePassword"
    redis:
      enabled: true
