---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/keda.sh/scaledobject_v1alpha1.json
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ${APP}
spec:
  advanced:
    restoreToOriginalReplicaCount: true
  cooldownPeriod: 0
  minReplicaCount: 0
  maxReplicaCount: 1
  scaleTargetRef:
    name: ${APP}
  triggers:
    - name: nas_health
      type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.observability.svc.cluster.local:9090
        query: min(probe_success{job="${ZEROSCALER_JOB_NAME:=nfs_probe}"})
        threshold: "1"
        activationThreshold: "0"
