apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: radarr
    template:
      data:
        RADARR__AUTH__APIKEY: "{{ .radarr_api_key }}"
  dataFrom:
    - extract:
        key: radarr
