---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/maintenance_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: Maintenance
metadata:
  name: nas
spec:
  ownership:
    owner: kopiur/nas
    takeoverPolicy: Force
  repository:
    kind: ClusterRepository
    name: nas
  schedule:
    quick:
      cron: H */6 * * *
    full:
      cron: H 5 * * *
