---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: common-data
spec:
  externalSecretName: common-data
  namespaceSelectors:
    - matchLabels:
        common-data: "true"
  refreshTime: "1h"
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword
    refreshInterval: "1h"
    target:
      name: common-data
      template:
        data:
          domain: "{{ .domain }}"
          email: "{{ .email }}"
          vault_source: "{{ .vault_source }}"
    dataFrom:
      - extract:
          key: common-k8s
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: vault-creds
spec:
  externalSecretName: vault-creds
  namespaceSelectors:
    - matchLabels:
        common-data: "true"
  refreshTime: "1h"
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword
    refreshInterval: "1h"
    target:
      name: vault-creds
      template:
        data:
          username: "{{ .share_username }}"
          password: "{{ .share_password }}"
    dataFrom:
      - extract:
          key: hetzner
