---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thanos-objstore
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: thanos-objstore
    template:
      data:
        objstore.yml: |-
          type: s3
          config:
            bucket: "{{ .bucket }}"
            endpoint: "{{ .endpoint }}"
            access_key: "{{ .access_key }}"
            secret_key: "{{ .secret_key }}"
  dataFrom:
    - extract:
        key: thanos
