apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: main-gateway
  annotations:
    cert-manager.io/issuer: letsencryt
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      oci.oraclecloud.com/load-balancer-type: "nlb"
      oci-network-load-balancer.oraclecloud.com/oci-network-security-groups: ${lb_nsg_id}
  listeners:
    - name: http
      port: 80
      protocol: HTTP
    - name: domain-https
      hostname: ${domain}
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: domain-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: wildcard-domain-https
      hostname: "*.${domain}"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: domain-tls
      allowedRoutes:
        namespaces:
          from: All
