---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: victoria-logs-mcp
spec:
  env:
    - name: MCP_SERVER_MODE
      value: http
    - name: MCP_LISTEN_ADDR
      value: :8081
    - name: MCP_LOG_FORMAT
      value: json
    - name: MCP_LOG_LEVEL
      value: info
    - name: VL_INSTANCE_ENTRYPOINT
      value: http://victoria-logs-server.observability.svc.cluster.local:9428
  groupRef:
    name: mcp-tools
  image: ghcr.io/victoriametrics/mcp-victorialogs:latest
  mcpPort: 8081
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          resources:
            limits:
              memory: 224Mi
            requests:
              cpu: 10m
              memory: 160Mi
  permissionProfile:
    type: builtin
    name: network
  transport: streamable-http
  resources:
    limits:
      memory: 48Mi
    requests:
      cpu: 10m
      memory: 24Mi
