---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mealie
    template:
      data:
        OIDC_CLIENT_SECRET: "{{ .mealie_oidc_client_secret }}"
  dataFrom:
    - extract:
        key: mealie
