apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./namespace.yaml
  - ./autobrr/ks.yaml
  - ./cross-seed/ks.yaml
  - ./nzbget/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./vault/ks.yaml
