---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: claude-code
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: claude-code-secret
    creationPolicy: Owner
    template:
      data:
        GH_TOKEN: "{{ .GH_TOKEN }}"
  dataFrom:
    - extract:
        key: hermes
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: claude-code-signing
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: claude-code-signing
    creationPolicy: Owner
    template:
      data:
        id_ed25519: "{{ .SSH_SIGNING_KEY }}"
  dataFrom:
    - extract:
        key: claude-code
