apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare
    template:
      data:
        api_token: "{{ .api_token }}"
  dataFrom:
    - extract:
        key: cloudflare
