---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kopia
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      kopia:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/kopia
              tag: 0.22.1@sha256:e3c243929e5625316275f316baadb6b478fe946ad711993c4282d0d28e5321fa
            env:
              KOPIA_WEB_ENABLED: true
              KOPIA_WEB_PORT: &port 8080
              TZ: Europe/Warsaw
            envFrom:
              - secretRef:
                  name: kopia
            args:
              - --without-password
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - "ALL"
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    configMaps:
      config:
        data:
          repository.config: |-
            {
              "storage": {
                "type": "filesystem",
                "config": {
                  "path": "/repository"
                }
              },
              "hostname": "volsync.volsync-system.svc.cluster.local",
              "username": "volsync",
              "description": "volsync",
              "enableActions": false
            }
    persistence:
      config-file:
        type: configMap
        identifier: config
        globalMounts:
          - path: /config/repository.config
            subPath: repository.config
      repository:
        type: custom
        volumeSpec:
          csi:
            driver: smb.csi.k8s.io
            volumeAttributes:
              source: //${vault_source}/Backup/aether
              secretName: vault-creds
              mountOptions: dir_mode=0777,file_mode=0777,uid=1001,gid=1001,noperm,mfsymlinks,cache=strict,noserverino
        globalMounts:
          - path: /repository
      tmpfs:
        type: emptyDir
        advancedMounts:
          kopia:
            app:
              - path: /config/cache
                subPath: cache
              - path: /config/logs
                subPath: logs
              - path: /tmp
                subPath: tmp
