---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vault
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: vault
  storageClassName: hetzner-smb
