---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nginx
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    nginxGateway:
      gwAPIExperimentalFeatures:
        enabled: true
    gateways:
      - name: nginx-gateway
        namespace: network
        # annotations:
        #   cert-manager.io/issuer: letsencrypt
        #   external-dns.alpha.kubernetes.io/target: ${public_ip}
        #   external-dns-managed: "true"
        spec:
          gatewayClassName: nginx
          infrastructure:
            annotations:
              lbipam.cilium.io/sharing-key: main
          listeners:
            - name: factorio
              protocol: UDP
              port: 34197
              allowedRoutes:
                kinds:
                  - kind: UDPRoute
                namespaces:
                  from: All
