---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: nas-memory-high-utilization
spec:
  matchers:
    - name: alertname
      value: NodeMemoryHighUtilization
    - name: instance
      value: bigmouth.internal:9100
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: hpa-maxed-out
spec:
  matchers:
    - name: alertname
      value: KubeHpaMaxedOut
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: kube-memory-overcommit
spec:
  matchers:
    - name: alertname
      value: KubeMemoryOvercommit
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: bigmouth-smart-device-interface-slow
spec:
  matchers:
    - name: alertname
      value: SmartDeviceInterfaceSlow
    - name: instance
      value: bigmouth.internal:9633
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: flux-instance-artifact-failed
spec:
  matchers:
    - name: alertname
      value: FluxFluxInstanceArtifactfailed
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: flux-oci-repository-ociartifact-pull-failed
spec:
  matchers:
    - name: alertname
      value: FluxOCIRepositoryOciartifactpullfailed
