apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: aether
spec:
  hostname: aether
  subnetRouter:
    advertiseRoutes:
      - "10.244.0.0/16"  # Pods
      - "10.96.0.0/16"   # Services
