apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nzbget
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      nzbget:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/nzbget
              tag: 25.3.0
            env:
              NZBGET__PORT: &port 8080
              TZ: Europe/Warsaw
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /jsonrpc/status
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: 
                drop: ["ALL"]
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 8Gi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
      media:
        existingClaim: vault
        globalMounts:
          - path: /vault/Downloads/nzbget
            subPath: Downloads/nzbget
      tmpfs:
        type: emptyDir
        advancedMounts:
          nzbget:
            app:
              - path: /tmp
                subPath: tmp
