apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
spec:
  interval: 30m
  chart:
    spec:
      chart: gateway
      version: 1.26.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    service:
      type: LoadBalancer
      annotations:
        oci.oraclecloud.com/load-balancer-type: "nlb"
        oci-network-load-balancer.oraclecloud.com/oci-network-security-groups: "${lb_nsg_id}"
        service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
        service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
        service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
      ports:
        - name: http
          port: 80
          targetPort: 8080
        - name: https
          port: 443
          targetPort: 8443
        - name: game-tcp-7777
          port: 7777
          protocol: TCP
        - name: game-udp-7777
          port: 7777
          protocol: UDP
        - name: game-tcp-8888
          port: 8888
          protocol: TCP
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
    podAnnotations:
      proxy.istio.io/config: |
        proxyMetadata:
          ISTIO_META_DEFAULT_CONFIG: |
            concurrency: 2
            protocolDetectionTimeout: 100ms
