---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app onepassword
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    connect:
      api:
        imageRepository: ghcr.io/1password/connect-api
        serviceMonitor:
          enabled: true
          interval: 1m
      sync:
        imageRepository: ghcr.io/1password/connect-sync
      applicationName: *app
      serviceType: ClusterIP
      credentialsName: op-credentials
      credentialsKey: 1password-credentials.json
      version: 1.7.4 # Current `1.7.3` not available on `ghcr.io`.
