apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: aetherdb
spec:
  description: "AetherDB - Main DB for the Aether Cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6-minimal-trixie
  instances: 3
  primaryUpdateStrategy: unsupervised
  # https://github.com/cloudnative-pg/cloudnative-pg/issues/5032#issuecomment-2491595856
  enableSuperuserAccess: false
  superuserSecret:
    name: superuser-db
  storage:
    size: 10Gi
  managed:
    roles:
    - name: authelia
      ensure: present
      login: true
      passwordSecret:
        name: authelia-db
    - name: lldap
      ensure: present
      login: true
      passwordSecret:
        name: lldap-db
  backup:
    retentionPolicy: 30d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://cnpg-aether/aetherdb/
      endpointURL: https://fsn1.your-objectstorage.com/
      # Note: serverName version needs to be inclemented
      # when recovering from an existing cnpg cluster
      serverName: &currentCluster aetherdb-v1
      s3Credentials:
        accessKeyId:
          name: s3-creds
          key: access_key
        secretAccessKey:
          name: s3-creds
          key: secret_key

  # # Note: previousCluster needs to be set to the name of the previous
  # # cluster when recovering from an existing cnpg cluster
  # bootstrap:
  #   recovery:
  #     source: &previousCluster aetherdb-v0
  # # Note: externalClusters is needed when recovering from an existing cnpg cluster
  # externalClusters:
  #   - name: *previousCluster
  #     barmanObjectStore:
  #       <<: *barmanObjectStore
  #       serverName: *previousCluster
