apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: aetherdb
spec:
  description: "AetherDB - Main DB for the Aether Cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6-minimal-trixie
  instances: 3
  primaryUpdateStrategy: unsupervised
  # https://github.com/cloudnative-pg/cloudnative-pg/issues/5032#issuecomment-2491595856
  enableSuperuserAccess: false
  superuserSecret:
    name: superuser-db
  storage:
    size: 10Gi
  managed:
    roles:
    - name: authelia
      ensure: present
      login: true
      passwordSecret:
        name: authelia-db
    - name: lldap
      ensure: present
      login: true
      passwordSecret:
        name: lldap-db
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: aetherdb

  # # Note: previousCluster needs to be set to the name of the previous
  # # cluster when recovering from an existing cnpg cluster
  # bootstrap:
  #   recovery:
  #     source: &previousCluster aetherdb-v0
  # # Note: externalClusters is needed when recovering from an existing cnpg cluster
  # externalClusters:
  # - name: *previousCluster
  #   plugin:
  #     name: barman-cloud.cloudnative-pg.io
  #     parameters:
  #       barmanObjectName: aetherdb
  #       serverName: *previousCluster
