apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: aetherdb
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: aetherdb
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
