---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./pocketidinstance.yaml
  - ./snapshot-migrate.yaml
patches:
  - target:
      kind: ScaledObject
    patch: |
      - op: add
        path: /metadata/annotations/autoscaling.keda.sh~1paused-replicas
        value: "0"
