---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDInstance
metadata:
  name: &app pocket-id
spec:
  image: ghcr.io/pocket-id/pocket-id:v2.9.0-distroless@sha256:e21b13437a542080f8226e4c6281ca26c7909123886606bf967f92e620d73f24
  timezone: Europe/Warsaw
  appUrl: "https://id.janpuc.com"
  databaseUrl:
    valueFrom:
      secretKeyRef:
        name: &secret pocket-id-secret
        key: DB_CONNECTION_STRING
  encryptionKey:
    valueFrom:
      secretKeyRef:
        name: *secret
        key: ENCRYPTION_KEY
  env:
    - name: LDAP_USER_SEARCH_FILTER
      valueFrom:
        secretKeyRef:
          name: *secret
          key: LDAP_USER_SEARCH_FILTER
    - name: LDAP_GROUPS_SEARCH_FILTER
      valueFrom:
        secretKeyRef:
          name: *secret
          key: LDAP_GROUPS_SEARCH_FILTER
  ldap:
    url: "ldap://lldap.security.svc.cluster.local:3890"
    base: dc=janpuc,dc=com
    bindDN: uid=admin,ou=people,dc=janpuc,dc=com
    bindPassword:
      valueFrom:
        secretKeyRef:
          name: *secret
          key: LDAP_BIND_PASSWORD
    skipCertVerify: true
    adminGroupName: "ID-Admin"
    attributeMapping:
      userUniqueIdentifier: "uuid"
      groupUniqueIdentifier: "uuid"
      userFirstName: "givenName"
      userLastName: "sn"
      userUsername: "uid"
      userEmail: "mail"
      userProfilePicture: "jpegPhoto"
      groupMember: "member"
      groupName: "cn"
  smtp:
    host: "smtp.protonmail.ch"
    port: 587
    from: "noreply@janpuc.com"
    user: "noreply@janpuc.com"
    password:
      valueFrom:
        secretKeyRef:
          name: *secret
          key: SMTP_PASSWORD
    tls: "starttls"
  geoip:
    dbPath: "/app/data/GeoLite2-City.mmdb"
    maxmindLicenseKey:
      valueFrom:
        secretKeyRef:
          name: *secret
          key: MAXMIND_LICENSE_KEY
  ui:
    sessionDuration: 43800
  userManagement:
    emailsVerified: true
  logging:
    level: "info"
  metrics:
    enabled: true
  analyticsDisabled: true
  versionCheckDisabled: true
  route:
    enabled: true
    parentRefs:
      - name: envoy-external
        namespace: network
    hostnames:
      - id.janpuc.com
  persistence:
    enabled: true
    existingClaim: *app
  resources:
    requests:
      cpu: 10m
      memory: 48Mi
    limits:
      memory: 96Mi
