---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch-operator
  labels:
    app.kubernetes.io/name: dispatch-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dispatch-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dispatch-operator
    spec:
      serviceAccountName: dispatch-operator
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: operator
          image: ghcr.io/janpuc/dispatch-operator:main
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          ports:
            - name: metrics
              containerPort: 8080
            - name: health
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 256Mi
