---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./crds/dispatch.janpuc.com_agents.yaml
  - ./crds/dispatch.janpuc.com_sessions.yaml
  - ./crds/dispatch.janpuc.com_triggers.yaml
  - ./crds/dispatch.janpuc.com_workspaces.yaml
  - ./rbac.yaml
  - ./externalsecret.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./servicemonitor.yaml
