---
apiVersion: v1
kind: Service
metadata:
  name: dispatch-operator
  labels:
    app.kubernetes.io/name: dispatch-operator
spec:
  selector:
    app.kubernetes.io/name: dispatch-operator
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
