---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: t3-code-smb
spec:
  length: 32
  noUpper: false
  digits: 6
  symbols: 4
  symbolCharacters: "-_"
  allowRepeat: true
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: t3-code-smb
spec:
  refreshPolicy: CreatedOnce
  target:
    name: t3-code-smb
    creationPolicy: Orphan
    immutable: true
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: t3-code-smb
