---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: recyclarr
    template:
      data:
        RADARR_API_KEY: "{{ .radarr_api_key }}"
        SONARR_API_KEY: "{{ .sonarr_api_key }}"
  dataFrom:
    - extract:
        key: radarr
    - extract:
        key: sonarr
