apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: mealie
spec:
  target:
    service: mealie
    port: 9000
  rules:
    - hosts:
        - recipes.janpuc.com
        - mealie.janpuc.com
  scalingMetric:
    concurrency:
      targetValue: 100
  timeouts:
    request: 60s
    responseHeader: 30s
    readiness: 15s
