apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    installCRDs: true
  image:
    repository: ghcr.io/tailscale/k8s-operator
    tag: v1.78.3
