---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: id-admin
spec:
  name: "ID-Admin"
---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: id-users
spec:
  name: "ID-Users"
