apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: prowlarr
    template:
      data:
        PROWLARR__AUTH__APIKEY: "{{ .api_key }}"
  dataFrom:
    - extract:
        key: prowlarr
