---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dispatch
spec:
  chartRef:
    kind: OCIRepository
    name: dispatch
  interval: 30m
  values:
    image:
      tag: main@sha256:ad0cc3336983d8ebb5dfc78a8c7e35358fe1a169e1bc8f4f0267071b16e1078a
      pullPolicy: IfNotPresent
    serviceMonitor:
      enabled: true
