apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app proxmox-csi
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    existingConfigSecret: proxmox-csi
    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
    storageClass:
      - name: proxmox-ssd
        storage: local-lvm
        ssd: "true"
        reclaimPolicy: Delete
        fstype: ext4
      - name: proxmox-hdd
        storage: hdd-drive
        reclaimPolicy: Delete
        fstype: ext4
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
