---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: prometheus-mcp
spec:
  image: ghcr.io/pab1it0/prometheus-mcp-server:1.6.1
  groupRef:
    name: mcp-tools
  env:
    - name: PROMETHEUS_URL
      value: http://prometheus-operated.observability.svc.cluster.local:9090
    - name: PROMETHEUS_DISABLE_LINKS
      value: "true"
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          resources:
            limits:
              memory: 224Mi
            requests:
              cpu: 10m
              memory: 160Mi
  resources:
    limits:
      memory: 96Mi
    requests:
      cpu: 10m
      memory: 48Mi
  transport: stdio
