---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app factorio
  namespace: &namespace games
spec:
  components:
    - ../../../../../components/volsync
  interval: 1h
  path: ./kubernetes-legacy/apps/aether/games/factorio/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 20Gi
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
