---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app thanos
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    existingObjstoreSecret: thanos-objstore
    query:
      enabled: true
      dnsDiscovery:
        enabled: false
      extraFlags:
        - --endpoint=dnssrv+_grpc._tcp.kube-prometheus-stack-thanos-discovery.observability.svc.clusterset.local
      networkPolicy:
        enabled: false
    receive:
      enabled: false
    storegateway:
      enabled: true
      networkPolicy:
        enabled: false
      persistence:
        enabled: true
        storageClass: proxmox-ssd
        size: 10Gi
    compactor:
      enabled: true
      networkPolicy:
        enabled: false
      persistence:
        enabled: true
        storageClass: proxmox-ssd
        size: 20G
    queryFrontend:
      enabled: true
      networkPolicy:
        enabled: false
    ruler:
      enabled: false
    bucketweb:
      enabled: false
