---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshot_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: Snapshot
metadata:
  name: ${APP}-local-proof
spec:
  deletionPolicy: Retain
  policyRef:
    name: ${APP}
