---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: mealie
spec:
  name: Mealie
  callbackUrls:
    - "https://recpies.janpuc.com/"
    - "https://recpies.janpuc.com/login"
    - "https://recpies.janpuc.com/login?direct=1"
  allowedUserGroups:
    - name: id-admin
      namespace: security
  secret:
    keys:
      clientID: OIDC_CLIENT_ID
      clientSecret: OIDC_CLIENT_SECRET
