apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autobrr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: autobrr
    template:
      data:
        AUTOBRR__OIDC_CLIENT_SECRET: "{{ .autobrr_oidc_client_secret }}"
  dataFrom:
    - extract:
        key: autobrr
