---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  chartRef:
    kind: OCIRepository
    name: open-webui
  interval: 30m
  values:
    controllers:
      open-webui:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: v0.10.2@sha256:9fcea9c6e32ab60b0498f3986c6cdf651ddbe61db48d2213a3d28048ddd673d4
            env:
              # OAuth
              ENABLE_OAUTH_SIGNUP: true
              ENABLE_OAUTH_PERSISTENT_CONFIG: false
              OAUTH_MERGE_ACCOUNTS_BY_EMAIL: true
              OAUTH_UPDATE_PICTURE_ON_LOGIN: true
              OAUTH_PROVIDER_NAME: "Pocket ID"
              OAUTH_SCOPES: "openid profile email groups"
              OPENID_PROVIDER_URL: https://id.janpuc.com/.well-known/openid-configuration
              OPENID_REDIRECT_URI: https://chat.janpuc.com/oauth/oidc/callback
              # Features
              ENABLE_LOGIN_FORM: false
              ENABLE_OLLAMA_API: false
              ENABLE_OPENAI_API: false
              ENABLE_RAG_WEB_SEARCH: true
              ENABLE_SEARCH_QUERY: true
              ENABLE_SIGNUP: false
              # Search
              RAG_WEB_SEARCH_ENGINE: searxng
              SEARXNG_QUERY_URL: http://searxng.selfhosted.svc.cluster.local:8080/search?q=<query>
              # Websockets
              ENABLE_WEBSOCKET_SUPPORT: true
              WEBSOCKET_MANAGER: redis
              WEBSOCKET_REDIS_URL: redis://open-webui-dragonfly:6379
            envFrom:
              - secretRef:
                  name: open-webui-secret
              - secretRef:
                  name: open-webui-oidc-credentials
            resources:
              requests:
                cpu: 100m
                memory: 1024Mi
              limits:
                memory: 1536Mi
    persistence:
      config:
        enabled: true
        existingClaim: open-webui
        globalMounts:
          - path: /app/backend/data
    route:
      app:
        hostnames:
          - chat.janpuc.com
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 8080
