---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: koment
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: koment-secret
    creationPolicy: Owner
    template:
      data:
        github-token: "{{ .KOMENT_GITHUB_TOKEN }}"
        credentials.yaml: |
          version: 1
          tokens:
            - name: hermes
              sha256: {{ .KOMENT_HERMES_TOKEN_SHA256 }}
              repositories:
                - home-ops
              permissions:
                - read
                - write
  dataFrom:
    - extract:
        key: koment
