---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plex
spec:
  components:
    - ../../../../components/zeroscaler
    - ../../../../components/gpu
    - ../../../../components/kopiur/backup
  dependsOn:
    - name: k8s-gpu-dra-driver
      namespace: kube-system
    - name: miroir-config
      namespace: miroir-system
  interval: 1h
  patches:
    - target:
        kind: Restore
        name: plex
      patch: |
        - op: replace
          path: /spec/source
          value:
            snapshotRef:
              name: plex-20260903101700
        - op: replace
          path: /spec/policy/onMissingSnapshot
          value: Fail
  path: ./kubernetes/apps/media/plex/app
  postBuild:
    substitute:
      APP: plex
      KOPIUR_CAPACITY: 50Gi
      KOPIUR_COPYMETHOD: Direct
      KOPIUR_RESTORE_OFFSET: "5"
      KOPIUR_STORAGECLASS: miroir-fast-local
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
